config/routes.rb
BnegajiForum::Application.routes.draw do
  resources :settings

  resources :static_pages
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:new, :create]
  resources :forums do
    resources :topics
  end

  get "users/new"

  root to:"static_pages#home"

  #여기는 resources 추가가 필요한 부분
  #this code is needed resources :static_pages
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"


  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/setting', to: 'settings#index'
end

app/models/forum.rb
# == Schema Info
#
# Table name: forums
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Forum < ActiveRecord::Base
  attr_accessible :description, :title
  has_many :topics, order: "created_at DESC"

  validates :title, presence: true
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  # GET /forums
  # GET /forums.xml
  def index
    @forums = Forum.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.xml
  def show
    @forum = Forum.find(params[:id])
    @topics = @forum.topics.paginate(page: params[:page])
    respond_to do |format|
      format.html { }# show.html.erb
      format.xml  { render :xml => @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.xml
  def new
    @forum = Forum.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.xml
  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to(@forum) }
        format.xml  { render :xml => @forum, :status => :created, :location => @forum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @forum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.xml
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to(@forum) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @forum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.xml
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to(forums_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "메뉴 이름" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "메뉴 설명" %><br />
    <%= f.text_area :description, :rows => 4, :cols => 60 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<% provide(:title,'Forum')%>
<div style="width:50%;float:left;">
  <h1> 게시판 리스트</h1>
  <table>
    <tr>
  <% @forums.each do |forum| %>
    <td><%= button_to forum.title, forum_path(forum),method: :get,class: "btn btn-large btn-danger" %></td>
  <% end %>
    </tr>
  </table>
</div>

<table style="display:none">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forums.each do |forum| %>
  <tr>
    <td><%= forum.title %></td>
    <td><%= forum.description %></td>
    <td><%= link_to 'Show', forum %></td>
    <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
    <td><%= link_to 'Destroy', forum, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/forums/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<br/>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @forum.title %></h1>
<div class="center span12">
	<%= render 'topics/topic' %>
	<%= will_paginate @topics %>
</div>
<br/>

<div class ="span3"style="float:right;">
<% if admin? %>
<%= link_to 'Edit Forum', edit_forum_path(@forum) %> 
<% end %>

<%= button_to '글쓰기',new_forum_topic_path(@forum),method: :get,class: "btn btn-large btn-primary" %> 
</div>