config/routes.rb
BnegajiForum::Application.routes.draw do
  resources :settings

  resources :static_pages
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:new, :create]
  resources :forums do
    resources :topics
  end

  get "users/new"

  root to:"static_pages#home"

  #여기는 resources 추가가 필요한 부분
  #this code is needed resources :static_pages
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"


  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/setting', to: 'settings#index'
end

app/models/topic.rb
# == Schema Info
#
# Table name: topics
#
#  id                 :integer         not null, primary key
#  title              :string(255)
#  description        :text
#  forum_id           :integer
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  file_name          :string(255)
#  file_type          :string(255)
#  file_size          :integer
#  updated_time       :datetime
#  updatedtime        :date
#  comment_count      :decimal(, )
#  image_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  user_id            :integer
#  user_name          :string(255)
#  counter            :integer
#

class Topic < ActiveRecord::Base
  attr_accessible :description, :forum_id, :title, :image, :updated_time, :user_id, :user_name, :counter

  
  belongs_to :forum
  belongs_to :user
	has_many :comments
  validates :title, presence: true
  validates :description, presence: true
  validates :user_name, presence: true
	validates :user_id, presence: true
	default_scope order: 'topics.created_at DESC'
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :signed_in_user, only: [:show,:create, :destroy]

  before_filter :set_forums

  # GET /topics
  # GET /topics.xml
  def index
    @topics = @forum.topics
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments.all
    @comment = @topic.comments.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    #@topic = Topic.new
    @topic = @forum.topics.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = @forum.topics.create(params[:topic])
    #@topic = Topic.new(params[:topic])
    @topic.updated_time  = Time.now.to_s
    @topic.user_id = current_user.id
    @topic.user_name = current_user.name
    @topic.counter = 0 
    respond_to do |format|
      if @topic.save
        format.html { redirect_to(forum_path(@forum)) }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])
    @topic.updated_time  = Time.now.to_s
    @topic.user_id = current_user.id
    @topic.user_name = current_user.name

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(forum_topic_path(@forum, @topic)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end
  private

    def set_forums
      @forum = Forum.find(params[:forum_id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_comment.html.erb
<div class="comment"><%= comment.content %></div>

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

    <ul>
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :title ,"제목"%><br />
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description, "내용" %><br />
  <%= f.text_area :description, :rows => 4, :cols => 60 %>
</div>
<div class = "field">
  <%= f.label :image,"이미지" %>
  <%= f.file_field :image, rows:5, cols:10 %>

</div>

<div class="actions">
  <%= f.submit %>
</div>

app/views/topics/_topic.html.erb
<div id="topics">
  <table class = "table table-striped">
    <thead>
      <tr>
        <th style="width:5%;text-align:center;">작성자</th>
        <th style="width:10%;text-align:center;">날짜</th>
        <th style="width:5%;text-align:center;">조회</th>
        <th style="width:5%;text-align:center;">리플</th>
        <th style="width:75%;text-align:center;">제목</th>
        <th></th>      
      </tr>
    </thead>
  <ol reversed="reversed">
    <tbody>
      <% @topics.each do |topic| %>
        <tr class="<%= 'list_line'%>">
          <% if topic.user_name == current_user.name %>
            <td><span class="label"><%= topic.user_name %></span></td>
          <% else %>
            <td><span class="label label-important"><%= topic.user_name %></span></td>
          <% end %>
          <td><span class="label label-inverse"><%= topic.updated_at.strftime("%Y/%m/%d\n%I:%M%p") %></span></td>
          <td><%= topic.counter %></td>
          <td><% if topic.comments.exists? %>
            <span class="label label-warning"><%= topic.comments.count %></span></td>
          <% end %>
          <td><strong><%= link_to topic.title, forum_topic_path(@forum, topic) %></strong>
          <% if topic.image.exists? then %>
            <%= image_tag "/images/image_up.gif" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </ol>
  </table>
</div>

app/views/topics/_topicinfo.html.erb
<div id = "topicinfo">
	<h3 style="float:left;"><%= @topic.title %></h3>

  <table style="float:right;" >
  	<tr>
	  	<th><b>작성자</b></th>
  		<td><span class="label"><%= @topic.user_name %></span></td>
	  </tr>
  	<tr>
	  	<th><b>작성일</b></th>
  		<td><span class="label label-inverse"><%= @topic.updated_time.strftime("%Y/%m/%d\n%I:%M%p") %></span></td>
  	</tr>
    <tr>
      <th><b>조회수</b></th>
      <td><%= @topic.counter %></td>
    </tr>
	</table>  
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>
<%= form_for([@forum, @topic],html: {multipart: true}) do |f| %>
	<%= render 'form',f: f %>
<% end %>
<br/>

<%= link_to '뒤로가기', forum_topic_path(@forum, @topic) %> |
<%= link_to '게시판 선택', forum_path(@forum) %>

app/views/topics/index.html.erb
<% provide(:title, 'Topics') %>

<h1>Listing topics</h1>
<h1><%=current_user.name %></h1>
<div>
  <ol reversed="reversed">
  <% @topics.each do |topic| %>
    <div class="topic">
        <li><span class="title"><%= link_to topic.title, forum_topic_path(@forum, topic) %></span>
        <span class="time"><%= topic.updated_time %></span>
        <% if !(topic.comments.count == 0) %>
        	<b><span class='comment'><%= topic.comments.count %></span></b></li>
      <% end %>
    </div>
  <% end %>
  </ol>
</div>
</div>
<br />
<div style="float:right;">
<%= button_to '글쓰기', new_forum_topic_path(@forum),class: "btn btn-large btn-primary" %> 
</div>

app/views/topics/new.html.erb
<h1>New topic</h1>
<%= form_for([@forum, @topic],html: {multipart: true}) do |f| %>
	<%= render 'form',f: f %>
<% end %>
<br/>

<%= link_to 'Forum Topics', forum_topics_path(@forum) %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
	<%= render "topicinfo"%>
	<% @topic.increment!(:counter) %>
<div>
	<% if @topic.image.exists? %>
		<%= image_tag @topic.image%>
	<% end %>
	<br/>
	<br/>
	<div class="hero-unit">
	  <%= raw RedCloth.new(coderay(@topic.description)).to_html %>
	</div>
</div>
<br/>
<%= render 'comments/form' %>
<br/>

<div id="comments">
	<ol>
 	 <%= render @comments %>
	</ol>
</div>
<br/>
<div style="float:right;">
	<table >
		<tr>
			<% if current_user.id.equal? @topic.user_id %>
				<td><%= button_to '글 수정', edit_forum_topic_path(@forum, @topic), method: :get, class:'btn btn-mini'%></td>
			<% end %>
				<td><%= button_to '처음으로', root_path, method: :get, class:'btn btn-mini'%></td>
				<td><%= button_to '목록으로', forum_path(@forum), method: :get,  class:'btn btn-mini'%></td>
		</tr>
	</table>
</div>