config/routes.rb
BnegajiForum::Application.routes.draw do
  resources :settings

  resources :static_pages
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:new, :create]
  resources :forums do
    resources :topics
  end

  get "users/new"

  root to:"static_pages#home"

  #여기는 resources 추가가 필요한 부분
  #this code is needed resources :static_pages
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"


  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/setting', to: 'settings#index'
end

app/models/setting.rb
# == Schema Info
#
# Table name: settings
#
#  id              :integer         not null, primary key
#  logostring      :string(255)
#  maindescription :text
#  mainimageurl    :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

class Setting < ActiveRecord::Base
  attr_accessible :logostring, :maindescription, :mainimageurl
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
    @forums = Forum.all
    @topics = Topic.all
    @comments = Comment.all
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_comments.html.erb
  <div class="setting">
      <h3>댓글</h3><br/>
      <table>
      <% Forum.all.each do |forum| %>
        <% forum.topics.each do |topic| %>
          <% topic.comments.each do |comment| %>
            <tr>
              <td><h5><%= comment.content %></h5></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
     </table>
  </div>

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logostring,"로고,타이틀" %><br />
    <%= f.text_field :logostring %>
  </div>
  <div class="field">
    <%= f.label :maindescription,"홈페이지 설명" %><br />
    <%= f.text_area :maindescription %>
  </div>
  <div class="field">
    <%= f.label :mainimageurl,"홈페이지 동영상(youtube source)" %><br />
    <%= f.text_field :mainimageurl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/_menus.html.erb
  <div class="setting">
      <h3>메뉴</h3><%= link_to '새 메뉴', new_forum_path ,class:"btn btn-small btn-primary"%>
      <table>
      <% Forum.all.each do |forum| %>
        <tr>
          <td><h4><%= forum.title %></h4></td>
          <td><%= button_to 'Show', forum, method: :get,class: "btn btn-primary" %></td>
          <td><%= button_to 'Edit', edit_forum_path(forum), method: :get, class: "btn btn-warning" %></td>
          <td><%= button_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
        </tr>
      <% end %>
      </table>
  </div>

app/views/settings/_summary.html.erb
  <div style="float:right;">
    <% if Setting.exists? %>
      <%= link_to '기본설정', edit_setting_path(1),class:"btn btn-primary" %>
    <% else %>
      <%= link_to '기본설정', new_setting_path,class:"btn btn-primary" %>
    <% end %>
  </div>
  <div id = "settingsummary">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>메뉴 수</th>
          <th>게시글 수</th>
          <th>사용자 수</th>
          <th>댓글 수</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= Forum.count %></td>
          <td><%= Topic.count %></td>
          <td><%= User.count %></td>
          <td><%= Comment.count %></td>
        </tr>
      </tbody>
    </table>
  </div>

app/views/settings/_topics.html.erb
  <div class="setting">
      <h3>게시글</h3><br/>
      <table>
      <% Forum.all.each do |forum| %>
        <% forum.topics.each do |topic| %>
          <tr>
            <td><h5><%= topic.title %></h5></td>
            <td><%= link_to 'Show',forum_topic_path(forum, topic), method: :get,class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_forum_topic_path(forum,topic), method: :get,class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', forum_topic_path(forum,topic), method: :delete, data: { confirm: 'Are you sure?' } , method: :get,class: "btn btn-danger"%>
          </tr>
        <% end %>
      <% end %>
     </table>
  </div>

app/views/settings/_users.html.erb
  <div class="setting">
    <h3>사용자</h3>
    <table>
      <% User.all.each do |user| %>
        <tr>
          <td><h4><%= user.name %></h4></td>
          <% if current_user.admin == false %>
          <td><%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Homepage Setting</h1>
  <%= render 'summary' %>
  <%= render 'menus' %>
  <%= render 'topics' %>
  <%= render 'comments' %>
  <%= render 'users' %>

app/views/settings/new.html.erb
<h1>Homepage Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Logostring:</b>
  <%= @setting.logostring %>
</p>

<p>
  <b>Maindescription:</b>
  <%= @setting.maindescription %>
</p>

<p>
  <b>Mainimageurl:</b>
  <%= @setting.mainimageurl %>
</p>


<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>