config/routes.rb
BnegajiForum::Application.routes.draw do
  resources :settings

  resources :static_pages
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :comments, only: [:new, :create]
  resources :forums do
    resources :topics
  end

  get "users/new"

  root to:"static_pages#home"

  #여기는 resources 추가가 필요한 부분
  #this code is needed resources :static_pages
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"


  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/setting', to: 'settings#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<h2 style="float:left;">Portolio</h2>
	<div style="float:right;"><h3>Make Your own Homepage!</h3>
	<h4>서울과학기술대학교, 박창주, 문혜림</h4></div>
</footer>

app/views/layouts/_forum.html.erb
<% Forum.all.each do |forum| %>
  <li><%= link_to forum.title, forum_path(forum) %></li>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <% if Setting.exists? %>
        <%= link_to Setting.first.logostring, root_path, id: "logo" %>
      <% else %>
        <%= link_to "Empty", root_path, id: "logo" %>   
      <% end %>
      

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- Be sure to leave the brand out there if you want it shown -->
      <!-- Everything you want hidden at 940px or less, place within here -->      
      <div  class="nav-collapse">
        <ul class="nav pull-right">
          <% if signed_in? %>
            <%= render "layouts/forum"%>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "User Edit", edit_user_path(current_user) %></li>
                <li><%= link_to "Homepage Setting", settings_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>    
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if Setting.exists? %>
        <%= Setting.first.logostring %>
      <% else %>
        Empty
      <% end %>
    </title>
    <%= stylesheet_link_tag    "application","coderay", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
		<%= render 'layouts/shim' %>    

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>